DB_NAME=network_monitor_local
DB_USER=myuser
DB_PASS=mypassword

ADD_REMOTE=y
REMOTE_DB_IP=127.0.0.1
REMOTE_DB_PORT=3306
REMOTE_DB_NAME=network_monitor
REMOTE_DB_USER=myuser
REMOTE_DB_PASS=mypassword
