apiVersion: 1

datasources:
  - name: LocalNetworkMonitor
    uid: LocalNetworkMonitor
    type: mysql
    access: proxy
    url: ${GRAFANA_DB_LOCAL_HOST}:${GRAFANA_DB_LOCAL_PORT}
    user: ${GRAFANA_DB_LOCAL_USER}
    secureJsonData:
      password: ${GRAFANA_DB_LOCAL_PASSWORD}
    jsonData:
      database: ${GRAFANA_DB_LOCAL_NAME}
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      tlsAuth: false

  - name: RemoteNetworkMonitor
    uid: RemoteNetworkMonitor
    type: mysql
    access: proxy
    url: ${GRAFANA_DB_REMOTE_HOST}:${GRAFANA_DB_REMOTE_PORT}
    user: ${GRAFANA_DB_REMOTE_USER}
    secureJsonData:
      password: ${GRAFANA_DB_REMOTE_PASSWORD}
    jsonData:
      database: ${GRAFANA_DB_REMOTE_NAME}
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      tlsAuth: false
